# gen_build_id.cmake — v1.2.2 build identity (Codex R2-6)
#
# Generates build_id.h with:
#   WSL_BUILD_GIT = `git describe --always --dirty --tags` of the repo
#   WSL_CFG_SHA   = sha256(config.h) first 8 hex chars
# Invoked at BUILD time by the wsl_build_id custom target (CMakeLists.txt), NOT
# at configure time — so a stale configure can never embed a stale identity.
# Writes via copy_if_different so an unchanged identity does not force a
# rebuild of main.c.
#
# Expected -D inputs: SRC_DIR (firmware/rp2040 source dir), OUT (build_id.h path).

execute_process(COMMAND git describe --always --dirty --tags
                WORKING_DIRECTORY ${SRC_DIR}
                OUTPUT_VARIABLE GIT_DESC
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
                RESULT_VARIABLE GIT_RC)
if(NOT GIT_RC EQUAL 0 OR GIT_DESC STREQUAL "")
    set(GIT_DESC "nogit")
endif()

file(SHA256 ${SRC_DIR}/config.h CFG_FULL)
string(SUBSTRING ${CFG_FULL} 0 8 CFG_SHA)

file(WRITE ${OUT}.tmp
"/* generated by gen_build_id.cmake (v1.2.2 R2-6) — DO NOT EDIT, DO NOT COMMIT */
#define WSL_BUILD_GIT \"${GIT_DESC}\"
#define WSL_CFG_SHA   \"${CFG_SHA}\"
")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${OUT}.tmp ${OUT})
file(REMOVE ${OUT}.tmp)
