#!/usr/bin/env python3
"""
Machine-readable netlist diff: rev-C (kicad/wsl-phase8b.net — read-only) vs
rev-D (kicad/wsl-phase8b-revD.net). Writes kicad/revD/netlist_diff_revC_to_revD.txt.

Identity model: SKiDL tags (the 'SKiDL Tag' netlist field) are the stable part
identity across revisions; numeric refdes shift when parts are inserted
mid-sequence and are reported separately as REFDES_SHIFT lines. Net node
membership is therefore compared as (tag, pin) sets, not (ref, pin).

Fails (exit 1) if anything OUTSIDE the documented rev-D contract changed:
  - any rev-C part removed, or its value/footprint changed (except the
    ALLOWED_CHANGED_PARTS whitelist: D_PROT SS14->SS34 per spec §H.4)
  - any rev-C net removed
  - any rev-C net changed other than the 11 documented touch-point nets
  - any touch-point net LOSING a rev-C node (additions only)
  - any added part/net not in the spec's expected-additions list

Run:  py -3 scripts\\diff_netlist_revC_to_revD.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REVC = os.path.join(ROOT, "kicad", "wsl-phase8b.net")
REVD = os.path.join(ROOT, "kicad", "wsl-phase8b-revD.net")
OUT_DIR = os.path.join(ROOT, "kicad", "revD")
OUT = os.path.join(OUT_DIR, "netlist_diff_revC_to_revD.txt")

# The only rev-C nets rev-D is allowed to touch (all additions-only), per
# docs/phase8_revD_change_spec.md items A/C/D/E/F:
ALLOWED_TOUCHED_NETS = {
    "FIELD_WET_V",    # A: bleed pair; C: 8 x Rin_AUXn
    "FIELD_GND",      # A: bleed pair; C: J15 pins 9-10
    "VCC_5V",         # D: divider top; F: J16 pin 1
    "GND",            # C: 8 x opto emitter; D: divider bottom + cap; E: 555 shunt; F: J16 pins 2,6
    "VCC_3V3",        # C: 8 x Rpu_AUXn; F: J16 pin 5
    "I2C_SDA",        # F: J16 pin 3
    "I2C_SCL",        # F: J16 pin 4
    "NE555_OUT",      # E: series tap resistor
    "WDOG_KICK",      # E: series tap resistor
    "ARM_PERMIT",     # E: series tap resistor
    "RP2040_OK",      # E: series tap resistor
}

EXPECTED_ADDED_TAGS = (
    ["R_WET_BLEED1", "R_WET_BLEED2"]                                   # A
    + [f"{p}_AUX{i}" for i in range(4, 12) for p in ("OPTO", "Rin", "Rpu")]  # C
    + ["J_SLOWC"]                                                      # C
    + ["R_ADC5_TOP", "R_ADC5_BOT", "C_ADC5"]                           # D
    + ["R_TAP_555", "R_TAP_555_DIV", "R_TAP_KICK", "R_TAP_ARM", "R_TAP_RPOK"]  # E
    + ["J_EXTI2C"]                                                     # F
)

EXPECTED_ADDED_NETS = (
    [f"{p}AUX{i}" for i in range(4, 12) for p in ("SLOW_", "FIELD_SLOW_", "FIELD_LED_")]  # C
    + ["ADC_VCC5_SENSE"]                                               # D
    + ["TAP_NE555_OUT", "TAP_WDOG_KICK", "TAP_ARM_PERMIT", "TAP_RP2040_OK"]  # E
)

# Documented rev-C part value changes (still reported as CHANGED_PART lines,
# but not PROBLEMs). Spec §H.4 / run-log FR-3: D_PROT SS14 (1 A) -> SS34
# (3 A, MDD C8678, same D_SMA footprint) — the rev-D worst case 0.73-0.93 A
# plus J16's 100 mA module allowance exceeds SS14's rating.
ALLOWED_CHANGED_PARTS = {
    "D_PROT": {("SS14", "Diode_SMD:D_SMA"): ("SS34", "Diode_SMD:D_SMA")},
}


def parse(path):
    text = open(path, encoding="utf-8").read()
    comps = {}   # tag -> (ref, value, footprint)
    ref2tag = {}
    for m in re.finditer(
            r'\(comp\s+\(ref "(?P<ref>[^"]+)"\)\s+\(value "(?P<val>[^"]*)"\).*?'
            r'\(footprint "(?P<fp>[^"]*)"\)(?P<rest>.*?)\(tstamps',
            text, re.S):
        tag_m = re.search(r'\(name "SKiDL Tag"\) "([^"]*)"', m.group("rest"))
        tag = tag_m.group(1) if tag_m else m.group("ref")
        comps[tag] = (m.group("ref"), m.group("val"), m.group("fp"))
        ref2tag[m.group("ref")] = tag

    nets = {}    # name -> set of (tag, pin)
    nets_text = text[text.index("(nets"):]
    for block in re.split(r'\(net\s+\(code\s', nets_text)[1:]:
        name = re.search(r'\(name "([^"]*)"\)', block).group(1)
        nodes = set()
        for nm in re.finditer(r'\(node\s+\(ref "([^"]+)"\)\s+\(pin "([^"]+)"\)', block):
            nodes.add((ref2tag.get(nm.group(1), nm.group(1)), nm.group(2)))
        nets[name] = nodes
    return comps, nets


def main():
    c_comps, c_nets = parse(REVC)
    d_comps, d_nets = parse(REVD)

    lines = []
    problems = []

    lines.append("# Netlist diff: rev-C (kicad/wsl-phase8b.net) -> rev-D (kicad/wsl-phase8b-revD.net)")
    lines.append("# Generated by scripts/diff_netlist_revC_to_revD.py. Identity = SKiDL tag.")
    lines.append("# Format: TAB-separated records; first field is the record type.")
    lines.append(f"SUMMARY\tparts_revC={len(c_comps)}\tparts_revD={len(d_comps)}\tnets_revC={len(c_nets)}\tnets_revD={len(d_nets)}")

    # ---- parts ----
    added_tags = sorted(set(d_comps) - set(c_comps))
    removed_tags = sorted(set(c_comps) - set(d_comps))
    for t in added_tags:
        ref, val, fp = d_comps[t]
        lines.append(f"ADDED_PART\t{t}\t{ref}\t{val}\t{fp}")
    for t in removed_tags:
        ref, val, fp = c_comps[t]
        lines.append(f"REMOVED_PART\t{t}\t{ref}\t{val}\t{fp}")
        problems.append(f"rev-C part removed: {t}")

    changed_parts = []
    shifts = []
    for t in sorted(set(c_comps) & set(d_comps)):
        cref, cval, cfp = c_comps[t]
        dref, dval, dfp = d_comps[t]
        if (cval, cfp) != (dval, dfp):
            changed_parts.append(t)
            lines.append(f"CHANGED_PART\t{t}\t{cval}|{cfp}\t->\t{dval}|{dfp}")
            if ALLOWED_CHANGED_PARTS.get(t, {}).get((cval, cfp)) == (dval, dfp):
                lines.append(f"NOTE\tdocumented value change (spec H.4 / run-log FR-3): {t}")
            else:
                problems.append(f"rev-C part value/footprint changed: {t}")
        if cref != dref:
            shifts.append(f"REFDES_SHIFT\t{t}\t{cref}\t{dref}")
    lines.extend(shifts)

    if sorted(added_tags) != sorted(EXPECTED_ADDED_TAGS):
        problems.append(f"added-part set != spec expectation: extra={sorted(set(added_tags)-set(EXPECTED_ADDED_TAGS))} missing={sorted(set(EXPECTED_ADDED_TAGS)-set(added_tags))}")

    # ---- nets ----
    added_nets = sorted(set(d_nets) - set(c_nets))
    removed_nets = sorted(set(c_nets) - set(d_nets))
    for n in added_nets:
        nodes = " ".join(f"{t}.{p}" for t, p in sorted(d_nets[n]))
        lines.append(f"ADDED_NET\t{n}\t{nodes}")
    for n in removed_nets:
        lines.append(f"REMOVED_NET\t{n}")
        problems.append(f"rev-C net removed: {n}")
    if sorted(added_nets) != sorted(EXPECTED_ADDED_NETS):
        problems.append(f"added-net set != spec expectation: extra={sorted(set(added_nets)-set(EXPECTED_ADDED_NETS))} missing={sorted(set(EXPECTED_ADDED_NETS)-set(added_nets))}")

    unchanged = 0
    for n in sorted(set(c_nets) & set(d_nets)):
        plus = sorted(d_nets[n] - c_nets[n])
        minus = sorted(c_nets[n] - d_nets[n])
        if not plus and not minus:
            unchanged += 1
            continue
        plus_s = " ".join(f"+{t}.{p}" for t, p in plus)
        minus_s = " ".join(f"-{t}.{p}" for t, p in minus)
        lines.append(f"CHANGED_NET\t{n}\t{(plus_s + ' ' + minus_s).strip()}")
        if n not in ALLOWED_TOUCHED_NETS:
            problems.append(f"undocumented rev-C net touched: {n} (+{plus} -{minus})")
        if minus:
            problems.append(f"touch-point net LOST rev-C nodes: {n} -{minus}")

    touched = [l.split("\t")[1] for l in lines if l.startswith("CHANGED_NET")]
    untouched_allowed = sorted(ALLOWED_TOUCHED_NETS - set(touched))
    lines.append(f"UNCHANGED_NETS\t{unchanged}")
    lines.append(f"TOUCHED_NETS\t{len(touched)}\t{' '.join(sorted(touched))}")
    if untouched_allowed:
        lines.append(f"NOTE\tallowed-touch nets not actually touched: {' '.join(untouched_allowed)}")

    for p in problems:
        lines.append(f"PROBLEM\t{p}")
    lines.append("RESULT\t" + ("CLEAN - all deltas match docs/phase8_revD_change_spec.md" if not problems
                               else f"{len(problems)} PROBLEM(S)"))

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWROTE {OUT}")
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
