from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

generate_kicad_netlist_revD = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'RaspberryPi_Pico', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RaspberryPi_Pico'}), 'ref_prefix':'A', 'fplist':['Module:RaspberryPi_Pico_Common_Unspecified'], 'footprint':'Module:RaspberryPi_Pico_SMD', 'keywords':'RP2350A M33 RISC-V Hazard3 usb', 'description':'Versatile and inexpensive microcontroller module powered by RP2040 dual-core Arm Cortex-M0+ processor up to 133 MHz, 264kB SRAM, 2MB QSPI flash; also supports Raspberry Pi Pico 2', 'datasheet':'https://datasheets.raspberrypi.com/pico/pico-datasheet.pdf', 'pins':[
            Pin(num='1',name='GPIO0',func=pin_types.BIDIR,unit=1),
            Pin(num='2',name='GPIO1',func=pin_types.BIDIR,unit=1),
            Pin(num='3',name='GND',func=pin_types.PWROUT,unit=1),
            Pin(num='4',name='GPIO2',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='GPIO3',func=pin_types.BIDIR,unit=1),
            Pin(num='6',name='GPIO4',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='GPIO5',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='GPIO6',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='GPIO7',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='GPIO8',func=pin_types.BIDIR,unit=1),
            Pin(num='12',name='GPIO9',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='GPIO10',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='GPIO11',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='GPIO12',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='GPIO13',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='19',name='GPIO14',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='GPIO15',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='GPIO16',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='GPIO17',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='24',name='GPIO18',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='GPIO19',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='GPIO20',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='GPIO21',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='29',name='GPIO22',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='RUN',func=pin_types.PASSIVE,unit=1),
            Pin(num='31',name='GPIO26_ADC0',func=pin_types.BIDIR,unit=1),
            Pin(num='32',name='GPIO27_ADC1',func=pin_types.BIDIR,unit=1),
            Pin(num='33',name='AGND',func=pin_types.PWROUT,unit=1),
            Pin(num='34',name='GPIO28_ADC2',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='ADC_VREF',func=pin_types.PWRIN,unit=1),
            Pin(num='36',name='3V3',func=pin_types.PWROUT,unit=1),
            Pin(num='37',name='3V3_EN',func=pin_types.PASSIVE,unit=1),
            Pin(num='38',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='39',name='VSYS',func=pin_types.PWRIN,unit=1),
            Pin(num='40',name='VBUS',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MCP23017x-x-SO', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MCP23017x-x-SO'}), 'ref_prefix':'U', 'fplist':['Package_SO:SOIC-28W_7.5x17.9mm_P1.27mm'], 'footprint':'Package_SO:SOIC-28W_7.5x17.9mm_P1.27mm', 'keywords':'Microchip port-expander GPIO', 'description':'16-bit I/O expander, I2C, interrupts, w pull-ups, GPA7/GPB7 output only (https://microchip.my.site.com/s/article/GPA7---GPB7-Cannot-Be-Used-as-Inputs-In-MCP23017),  SOIC-28', 'datasheet':'https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP23017-Data-Sheet-DS20001952.pdf', 'pins':[
            Pin(num='1',name='GPB0',func=pin_types.BIDIR,unit=1),
            Pin(num='2',name='GPB1',func=pin_types.BIDIR,unit=1),
            Pin(num='3',name='GPB2',func=pin_types.BIDIR,unit=1),
            Pin(num='4',name='GPB3',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='GPB4',func=pin_types.BIDIR,unit=1),
            Pin(num='6',name='GPB5',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='GPB6',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='GPB7',func=pin_types.OUTPUT,unit=1),
            Pin(num='9',name='V_{DD}',func=pin_types.PWRIN,unit=1),
            Pin(num='10',name='V_{SS}',func=pin_types.PWRIN,unit=1),
            Pin(num='11',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='12',name='SCK',func=pin_types.INPUT,unit=1),
            Pin(num='13',name='SDA',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='15',name='A0',func=pin_types.INPUT,unit=1),
            Pin(num='16',name='A1',func=pin_types.INPUT,unit=1),
            Pin(num='17',name='A2',func=pin_types.INPUT,unit=1),
            Pin(num='18',name='~{RESET}',func=pin_types.INPUT,unit=1),
            Pin(num='19',name='INTB',func=pin_types.TRISTATE,unit=1),
            Pin(num='20',name='INTA',func=pin_types.TRISTATE,unit=1),
            Pin(num='21',name='GPA0',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='GPA1',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='GPA2',func=pin_types.BIDIR,unit=1),
            Pin(num='24',name='GPA3',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='GPA4',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='GPA5',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='GPA6',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='GPA7',func=pin_types.OUTPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0805_2012Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'PC817', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PC817'}), 'ref_prefix':'U', 'fplist':['Package_DIP:DIP-4_W7.62mm'], 'footprint':'Package_DIP:DIP-4_W7.62mm', 'keywords':'NPN DC Optocoupler', 'description':'DC Optocoupler, Vce 35V, CTR 50-300%, DIP-4', 'datasheet':'http://www.soselectronic.cz/a_info/resource/d/pc817.pdf', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'G5LE-1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'G5LE-1'}), 'ref_prefix':'K', 'fplist':['Relay_THT:Relay_SPDT_Omron-G5LE-1'], 'footprint':'Relay_THT:Relay_SPDT_Omron-G5LE-1', 'keywords':'Miniature Single Pole Relay', 'description':'Omron G5LE relay, Miniature Single Pole, SPDT, 10A', 'datasheet':'http://www.omron.com/ecb/products/pdf/en-g5le.pdf', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MMBT3904', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MMBT3904'}), 'ref_prefix':'Q', 'fplist':['', 'Package_TO_SOT_SMD:SOT-23'], 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':'NPN Transistor', 'description':'0.2A Ic, 40V Vce, Small Signal NPN Transistor, SOT-23', 'datasheet':'https://www.onsemi.com/pdf/datasheet/pzt3904-d.pdf', 'pins':[
            Pin(num='1',name='B',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='E',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='C',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_SMD:D_SOD-323', 'keywords':'diode', 'description':'Diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Q_NMOS_GSD', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Q_NMOS_GSD'}), 'ref_prefix':'Q', 'fplist':[''], 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':'transistor NMOS N-MOS N-MOSFET', 'description':'N-MOSFET transistor, gate/source/drain', 'datasheet':'', 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='D',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'NE555D', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NE555D'}), 'ref_prefix':'U', 'fplist':['Package_SO:SOIC-8_3.9x4.9mm_P1.27mm'], 'footprint':'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'keywords':'single timer 555', 'description':'Precision Timers, 555 compatible, SOIC-8', 'datasheet':'http://www.ti.com/lit/ds/symlink/ne555.pdf', 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='8',name='VCC',func=pin_types.PWRIN),
            Pin(num='2',name='TRIG',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='OUT',func=pin_types.OUTPUT,unit=1),
            Pin(num='4',name='~{RST}',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='CONT',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='THRES',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='DISCH',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C_Polarized', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_Polarized'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:CP_Elec_6.3x5.4', 'keywords':'cap capacitor', 'description':'Polarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_02x10_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x10_Odd_Even'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_IDC:IDC-Header_2x10_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, double row, 02x10, odd/even pin numbering scheme (row 1 odd numbers, row 2 even numbers), script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='Pin_13',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='Pin_14',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='Pin_15',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='Pin_16',func=pin_types.PASSIVE,unit=1),
            Pin(num='17',name='Pin_17',func=pin_types.PASSIVE,unit=1),
            Pin(num='18',name='Pin_18',func=pin_types.PASSIVE,unit=1),
            Pin(num='19',name='Pin_19',func=pin_types.PASSIVE,unit=1),
            Pin(num='20',name='Pin_20',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x03', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x03'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-3-5.08_1x03_P5.08mm_Horizontal', 'keywords':'connector', 'description':'Generic connector, single row, 01x03, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x10', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x10'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_Phoenix_MC:PhoenixContact_MCV_1,5_10-G-3.5_1x10_P3.50mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x10, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x14', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x14'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_Phoenix_MC:PhoenixContact_MCV_1,5_14-G-3.5_1x14_P3.50mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x14, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='Pin_13',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='Pin_14',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x12', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x12'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_Phoenix_MC:PhoenixContact_MCV_1,5_12-G-3.5_1x12_P3.50mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x12, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-2-5.08_1x02_P5.08mm_Horizontal', 'keywords':'connector', 'description':'Generic connector, single row, 01x02, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x06', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x06'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_Phoenix_MC:PhoenixContact_MCV_1,5_6-G-3.5_1x06_P3.50mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x06, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x04'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_Phoenix_MC:PhoenixContact_MCV_1,5_4-G-3.5_1x04_P3.50mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x04, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D_Schottky', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_Schottky'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_SMD:D_SMA', 'keywords':'diode Schottky', 'description':'Schottky diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TMA-0505S', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TMA-0505S'}), 'ref_prefix':'U', 'fplist':['Converter_DCDC:Converter_DCDC_TRACO_TMA-05xxS_12xxS_Single_THT'], 'footprint':'Converter_DCDC:Converter_DCDC_TRACO_TMA-05xxS_12xxS_Single_THT', 'keywords':'Traco isolated dc-dc not-regulated non-regulated single', 'description':'1W DC/DC converter unregulated, 4.5-5.5V input, 5V output voltage, 200mA output, 1.0kVDC isolation, SIP-7', 'datasheet':'https://www.tracopower.com/products/tma.pdf', 'pins':[
            Pin(num='1',name='+Vin',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='-Vin',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='-Vout',func=pin_types.PWROUT,unit=1),
            Pin(num='6',name='+Vout',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Q_PMOS_GSD', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Q_PMOS_GSD'}), 'ref_prefix':'Q', 'fplist':[''], 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':'transistor PMOS P-MOS P-MOSFET', 'description':'P-MOSFET transistor, gate/source/drain', 'datasheet':'', 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='D',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] })])